// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main-header': string;
  'search-form': string;
  'task': string;
  'task-name': string;
  'tasks': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
