// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data-row': string;
  'data-table': string;
}
export const cssExports: CssExports;
export default cssExports;
