// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'error-message': string;
  'left-forms': string;
  'required': string;
}
export const cssExports: CssExports;
export default cssExports;
